//
//  Country.swift
//  Eksplorator
//  Copyright © Eksplorator 2025 Patryk Neubauer. All rights reserved.

import Foundation
import SwiftUI

enum Country: String, CaseIterable {
    case afghanistan = "af"
    case albania = "al"
    case algeria = "dz"
    case americanSamoa = "as"
    case andorra = "ad"
    case angola = "ao"
    case anguilla = "ai"
    case antarctica = "aq"
    case antiguaAndBarbuda = "ag"
    case argentina = "ar"
    case armenia = "am"
    case aruba = "aw"
    case australia = "au"
    case austria = "at"
    case azerbaijan = "az"
    case bahamas = "bs"
    case bahrain = "bh"
    case bangladesh = "bd"
    case barbados = "bb"
    case belarus = "by"
    case belgium = "be"
    case belize = "bz"
    case benin = "bj"
    case bermuda = "bm"
    case bhutan = "bt"
    case bolivia = "bo"
    case bosniaAndHerzegovina = "ba"
    case botswana = "bw"
    case brazil = "br"
    case britishIndianOceanTerritory = "io"
    case brunei = "bn"
    case bulgaria = "bg"
    case burkinaFaso = "bf"
    case burundi = "bi"
    case cambodia = "kh"
    case cameroon = "cm"
    case canada = "ca"
    case capeVerde = "cv"
    case caymanIslands = "ky"
    case centralAfricanRepublic = "cf"
    case chad = "td"
    case chile = "cl"
    case china = "cn"
    case christmasIsland = "cx"
    case cocosIslands = "cc"
    case colombia = "co"
    case comoros = "km"
    case congo = "cg"
    case congoTheDemocraticRepublic = "cd"
    case cookIslands = "ck"
    case costaRica = "cr"
    case coteDIvoire = "ci"
    case croatia = "hr"
    case cuba = "cu"
    case cyprus = "cy"
    case czechRepublic = "cz"
    case denmark = "dk"
    case djibouti = "dj"
    case dominica = "dm"
    case dominicanRepublic = "do"
    case ecuador = "ec"
    case egypt = "eg"
    case elSalvador = "sv"
    case equatorialGuinea = "gq"
    case eritrea = "er"
    case estonia = "ee"
    case ethiopia = "et"
    case falklandIslands = "fk"
    case faroeIslands = "fo"
    case fiji = "fj"
    case finland = "fi"
    case france = "fr"
    case frenchGuiana = "gf"
    case frenchPolynesia = "pf"
    case gabon = "ga"
    case gambia = "gm"
    case georgia = "ge"
    case germany = "de"
    case ghana = "gh"
    case gibraltar = "gi"
    case greece = "gr"
    case greenland = "gl"
    case grenada = "gd"
    case guadeloupe = "gp"
    case guam = "gu"
    case guatemala = "gt"
    case guernsey = "gg"
    case guinea = "gn"
    case guineaBissau = "gw"
    case guyana = "gy"
    case haiti = "ht"
    case honduras = "hn"
    case hongKong = "hk"
    case hungary = "hu"
    case iceland = "is"
    case india = "in"
    case indonesia = "id"
    case iran = "ir"
    case iraq = "iq"
    case ireland = "ie"
    case isleOfMan = "im"
    case israel = "il"
    case italy = "it"
    case jamaica = "jm"
    case japan = "jp"
    case jersey = "je"
    case jordan = "jo"
    case kazakhstan = "kz"
    case kenya = "ke"
    case kiribati = "ki"
    case kuwait = "kw"
    case kyrgyzstan = "kg"
    case laos = "la"
    case latvia = "lv"
    case lebanon = "lb"
    case lesotho = "ls"
    case liberia = "lr"
    case libya = "ly"
    case liechtenstein = "li"
    case lithuania = "lt"
    case luxembourg = "lu"
    case macao = "mo"
    case macedonia = "mk"
    case madagascar = "mg"
    case malawi = "mw"
    case malaysia = "my"
    case maldives = "mv"
    case mali = "ml"
    case malta = "mt"
    case marshallIslands = "mh"
    case martinique = "mq"
    case mauritania = "mr"
    case mauritius = "mu"
    case mayotte = "yt"
    case mexico = "mx"
    case micronesia = "fm"
    case moldova = "md"
    case monaco = "mc"
    case mongolia = "mn"
    case montenegro = "me"
    case montserrat = "ms"
    case morocco = "ma"
    case mozambique = "mz"
    case myanmar = "mm"
    case namibia = "na"
    case nauru = "nr"
    case nepal = "np"
    case netherlands = "nl"
    case newCaledonia = "nc"
    case newZealand = "nz"
    case nicaragua = "ni"
    case niger = "ne"
    case nigeria = "ng"
    case niue = "nu"
    case norfolkIsland = "nf"
    case northKorea = "kp"
    case northernMarianaIslands = "mp"
    case norway = "no"
    case oman = "om"
    case pakistan = "pk"
    case palau = "pw"
    case palestine = "ps"
    case panama = "pa"
    case papuaNewGuinea = "pg"
    case paraguay = "py"
    case peru = "pe"
    case philippines = "ph"
    case pitcairn = "pn"
    case poland = "pl"
    case portugal = "pt"
    case puertoRico = "pr"
    case qatar = "qa"
    case reunion = "re"
    case romania = "ro"
    case russia = "ru"
    case rwanda = "rw"
    case saintBarthelemy = "bl"
    case saintHelena = "sh"
    case saintKittsAndNevis = "kn"
    case saintLucia = "lc"
    case saintMartin = "mf"
    case saintPierreAndMiquelon = "pm"
    case saintVincentAndTheGrenadines = "vc"
    case samoa = "ws"
    case sanMarino = "sm"
    case saoTomeAndPrincipe = "st"
    case saudiArabia = "sa"
    case senegal = "sn"
    case serbia = "rs"
    case seychelles = "sc"
    case sierraLeone = "sl"
    case singapore = "sg"
    case slovakia = "sk"
    case slovenia = "si"
    case solomonIslands = "sb"
    case somalia = "so"
    case southAfrica = "za"
    case southGeorgiaAndTheSouthSandwichIslands = "gs"
    case southKorea = "kr"
    case southSudan = "ss"
    case spain = "es"
    case sriLanka = "lk"
    case sudan = "sd"
    case suriname = "sr"
    case svalbardAndJanMayen = "sj"
    case swaziland = "sz"
    case sweden = "se"
    case switzerland = "ch"
    case syria = "sy"
    case taiwan = "tw"
    case tajikistan = "tj"
    case tanzania = "tz"
    case thailand = "th"
    case timorLeste = "tl"
    case togo = "tg"
    case tokelau = "tk"
    case tonga = "to"
    case trinidadAndTobago = "tt"
    case tunisia = "tn"
    case turkey = "tr"
    case turkmenistan = "tm"
    case turksAndCaicosIslands = "tc"
    case tuvalu = "tv"
    case uganda = "ug"
    case ukraine = "ua"
    case unitedArabEmirates = "ae"
    case unitedKingdom = "gb"
    case unitedStates = "us"
    case uruguay = "uy"
    case uzbekistan = "uz"
    case vanuatu = "vu"
    case vatican = "va"
    case venezuela = "ve"
    case vietnam = "vn"
    case wallis = "wf"
    case westernSahara = "eh"
    case yemen = "ye"
    case zambia = "zm"
    case zimbabwe = "zw"
    
    var flagView: some View {
        Text(name)
            .font(.caption2)
            .frame(width: 24, height: 24)
            .background(Circle().fill(Color.gray))
            .overlay(
                Circle()
                    .stroke(Color.white.opacity(0.7), lineWidth: 1)
            )
    }
    
    private var name: String {
        let base : UInt32 = 127397
        var s = ""
        for v in rawValue.uppercased().unicodeScalars {
            s.unicodeScalars.append(UnicodeScalar(base + v.value)!)
        }
        return String(s)
    }
    
    var flag: String {
        let base : UInt32 = 127397
        var s = ""
        for v in rawValue.uppercased().unicodeScalars {
            s.unicodeScalars.append(UnicodeScalar(base + v.value)!)
        }
        return String(s)
    }
    
    var displayName: String {
        Locale.current.localizedString(forRegionCode: rawValue) ?? rawValue.uppercased()
    }
    
    static var sortedByName: [Country] {
        Self.allCases.sorted { $0.displayName < $1.displayName }
    }
}
